name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.EDP_GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'EEPTW',
              repo: 'EEPTW.github.io',
              workflow_id: '22664810',
              ref: 'main'
            });
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-2.12.0-4.1.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.12.0-4.1.pre
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
      - name: Build
        run: flutter build apk --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
          name: Android APK
  # Ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache flutter
  #       uses: actions/cache@v2
  #       with:
  #         path: /opt/hostedtoolcache/flutter
  #         key: ${{ runner.os }}-flutter-2.12.0-4.1.pre
  #     - uses: subosito/flutter-action@master
  #       with:
  #         channel: beta
  #         flutter-version: 2.12.0-4.1.pre
  #     - name: Build
  #       run: flutter build ipa --release
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         path: build/ios/archive
  #         name: Ios archive.zip
