name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'EDPTW',
              repo: 'EDPTW-APP',
              workflow_id: 'deploy.yaml',
              ref: 'main'
            });
